# Generated by Django 3.1.13 on 2021-07-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128)),
                ('card_network', models.CharField(max_length=128)),
                ('card_type', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('partial_card_number', models.CharField(max_length=128)),
                ('name_on_card', models.CharField(max_length=128)),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CardProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('logo_uri', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CardRunningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CardTransactionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_transaction_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(max_length=128)),
                ('transaction_category', models.CharField(max_length=128)),
                ('transaction_classification', models.JSONField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=128)),
                ('transaction_id', models.CharField(max_length=128)),
                ('provider_transaction_id', models.CharField(max_length=128)),
                ('normalised_provider_transaction_id', models.CharField(max_length=128)),
                ('merchant_name', models.CharField(max_length=128)),
                ('meta', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.card')),
                ('running_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cardrunningbalance')),
            ],
        ),
        migrations.CreateModel(
            name='CardBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=128)),
                ('available', models.FloatField()),
                ('current', models.FloatField()),
                ('credit_limit', models.FloatField()),
                ('last_statement_date', models.DateTimeField()),
                ('last_statement_balance', models.FloatField()),
                ('payment_due', models.FloatField()),
                ('payment_due_date', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cardprovider'),
        ),
    ]
