# Generated by Django 3.1.13 on 2021-08-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210804_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='running_balance',
            field=models.JSONField(),
        ),
    ]
