# Generated by Django 3.1.13 on 2021-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210804_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='normalised_provider_transaction_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='provider_transaction_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
