# Generated by Django 3.1.13 on 2021-08-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210804_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransactionPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(max_length=128)),
                ('transaction_category', models.CharField(max_length=128)),
                ('transaction_classification', models.JSONField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=128)),
                ('transaction_id', models.CharField(max_length=128)),
                ('provider_transaction_id', models.CharField(max_length=128, null=True)),
                ('normalised_provider_transaction_id', models.CharField(max_length=128, null=True)),
                ('running_balance', models.JSONField()),
                ('merchant_name', models.CharField(max_length=128)),
                ('meta', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.card')),
            ],
        ),
    ]
