# Generated by Django 3.1.13 on 2021-08-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_cardtransactionpending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtransactionpending',
            name='merchant_name',
        ),
        migrations.RemoveField(
            model_name='cardtransactionpending',
            name='normalised_provider_transaction_id',
        ),
        migrations.RemoveField(
            model_name='cardtransactionpending',
            name='provider_transaction_id',
        ),
        migrations.RemoveField(
            model_name='cardtransactionpending',
            name='running_balance',
        ),
    ]
