# Generated by Django 3.1.13 on 2021-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210804_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransactionpending',
            name='merchant_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cardtransactionpending',
            name='normalised_provider_transaction_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cardtransactionpending',
            name='provider_transaction_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cardtransactionpending',
            name='running_balance',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='merchant_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='running_balance',
            field=models.JSONField(null=True),
        ),
    ]
