# Generated by Django 3.1.13 on 2021-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210804_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128)),
                ('account_type', models.CharField(max_length=128)),
                ('account_number', models.JSONField(max_length=128)),
                ('currency', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('update_timestamp', models.DateTimeField()),
                ('provider', models.JSONField(max_length=128)),
            ],
        ),
    ]
