# Generated by Django 3.1.13 on 2021-08-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_accounttransaction_accounttransactionpending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accounttransactionpending',
            old_name='Account',
            new_name='account',
        ),
    ]
