# Generated by Django 3.1.13 on 2021-08-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_usercred_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercred',
            name='user',
        ),
    ]
